project_id = "atbrijpjxwklqtkgkast"

[functions.transcribe]
verify_jwt = false

[functions.complete]
verify_jwt = false

[functions.tts]
verify_jwt = false

[functions.realtime-chat]
verify_jwt = false

[functions.chat-memory-load]
verify_jwt = false

[functions.chat-memory-save]
verify_jwt = false